services:
  wallet-api:
    image: waltid/wallet-api:local
    build:
      context: ../
      dockerfile: waltid-services/waltid-wallet-api/Dockerfile
    pull_policy: never
    env_file:
      - .env
    extra_hosts:
      - "${SERVICE_HOST:-host.docker.internal}:host-gateway"
    volumes:
      - ./wallet-api/config:/waltid-wallet-api/config
