# This configuration file is used for setting up OIDC login
# with an OIDC server for the Web Wallet.
#
# OIDC in this file is exclusively related to login/authentication with the Web Wallet.
# It does not refer to any OIDC credential exchange protocol.

publicBaseUrl = "http://${SERVICE_HOST}:${DEMO_WALLET_FRONTEND_PORT}"

providerName = hanko
oidcRealm = "https://74b96159-f6f1-44dc-b39b-98380c67660f.hanko.io"
oidcJwks = "https://74b96159-f6f1-44dc-b39b-98380c67660f.hanko.io/.well-known/jwks.json"
oidcScopes = ["roles"]

authorizeUrl = "https://74b96159-f6f1-44dc-b39b-98380c67660f.hanko.io/oauth/authorize"
accessTokenUrl = "https://74b96159-f6f1-44dc-b39b-98380c67660f.hanko.io/oauth/token"
logoutUrl = ""

clientId = "__not_used_for_token_login__"
clientSecret = "__not_used_for_token_login__"

# JWKS is cached:
jwksCache = {
    cacheSize = 10
    cacheExpirationHours = 24
    rateLimit: {
        bucketSize: 10
        refillRatePerSecond: 10
        refillRateMinutes: 1
    }
}
